name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          #fqbn: 'arduino:samd'
          platforms: |
            - name: "arduino:samd"
          libraries: |
            - name: ArduinoBearSSL
            - name: ArduinoECCX08
            - name: utility/ECCX08SelfSignedCert
            - name: ArduinoMqttClient
            - name: WiFiNINA
          sketch-paths:
            "- devices/arduino"
